# [START discount-function-shopify.extension.api-version]
api_version = "2026-01"
# [END discount-function-shopify.extension.api-version]

# [START discount-function.toml.metadata]
[[extensions]]
name = "t:name"
handle = "discount-function-js"
uid = "9a3ff08f-70a9-f7e8-f33e-b015c1449d54"

type = "function"
description = "t:description"
# [END discount-function.toml.metadata]

# [START discount-function.toml.targets]
  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"
# [END discount-function.toml.targets]

# [START discount-function.toml.build]
  [extensions.build]
  command = ""
  path = "dist/function.wasm"
# [END discount-function.toml.build]
